version: "3.8"
services:
  web-app:
    build: .
    ports:
      - "3000:80"
    environment:
      - VITE_APP_FIREBASE_API_KEY=${REACT_APP_FIREBASE_API_KEY}
      - VITE_APP_FIREBASE_AUTH_DOMAIN=${REACT_APP_FIREBASE_AUTH_DOMAIN}
      - VITE_APP_FIREBASE_PROJECT_ID=${REACT_APP_FIREBASE_PROJECT_ID}
      - VITE_APP_FIREBASE_STORAGE_BUCKET=${REACT_APP_FIREBASE_STORAGE_BUCKET}
      - VITE_APP_FIREBASE_MESSAGING_SENDER_ID=${REACT_APP_FIREBASE_MESSAGING_SENDER_ID}
      - VITE_APP_FIREBASE_APP_ID=${REACT_APP_FIREBASE_APP_ID}
      - VITE_APP_FIREBASE_MEASUREMENT_ID=${REACT_APP_FIREBASE_MEASUREMENT_ID}